### ISSUE TITLE
VCSMap fails in plugin_list.rb

### ISSUE THREAD

**Issue by MBLAHO13** [melvinsh/vcsmap#7]
What I have done:
- Cloned the repo (Friday August 26th)
- Ran Bundle with an up-to-date bundle gem
- attempted to run `ruby vbsmap.rb filezilla_xml 2`

Below is the output:

```
mblaho@MBlahoCarbon:~/vcsmap$ bundle
Using addressable 2.4.0
Using coderay 1.1.1
Using unf_ext 0.0.7.2
Using equatable 0.5.0
Using http-form_data 1.0.1
Using http_parser.rb 0.6.0
Using method_source 0.8.2
Using mini_portile2 2.1.0
Using necromancer 0.3.0
Using pkg-config 1.1.7
Using tty-color 0.3.0
Using slop 3.6.0
Using require_all 1.3.3
Using tty-cursor 0.3.0
Using tty-screen 0.5.0
Using tty-which 0.1.0
Using unicode_utils 1.4.0
Using tty-platform 0.1.0
Using wisper 1.6.1
Using tty-spinner 0.2.0
Using bundler 1.12.5
Using unf 0.1.4
Using nokogiri 1.6.8
Using pastel 0.6.1
Using pry 0.10.4
Using tty-progressbar 0.9.0
Using verse 0.4.0
Using domain_name 0.5.20160615
Using tty-command 0.1.0
Using tty-prompt 0.6.0
Using tty-pager 0.4.0
Using tty-table 0.5.0
Using http-cookie 1.0.2
Using tty 0.5.0
Using http 2.0.3
Bundle complete! 5 Gemfile dependencies, 35 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
mblaho@MBlahoCarbon:~/vcsmap$ !ruby
ruby vcsmap.rb filezilla_xml 2
vcsmap.rb:11:in `require_relative': /home/mblaho/vcsmap/lib/plugin_list.rb:4: syntax error, unexpected ':', expecting => (SyntaxError)
       'wordpress_config': {
                          ^
/home/mblaho/vcsmap/lib/plugin_list.rb:8: syntax error, unexpected ',', expecting keyword_end
/home/mblaho/vcsmap/lib/plugin_list.rb:9: syntax error, unexpected ':', expecting keyword_end
       'google_oauth': {
                      ^
/home/mblaho/vcsmap/lib/plugin_list.rb:13: syntax error, unexpected ',', expecting keyword_end
/home/mblaho/vcsmap/lib/plugin_list.rb:14: syntax error, unexpected ':', expecting keyword_end
       'filezilla_xml': {
                       ^
/home/mblaho/vcsmap/lib/plugin_list.rb:18: syntax error, unexpected ',', expecting keyword_end
/home/mblaho/vcsmap/lib/plugin_list.rb:19: syntax error, unexpected ':', expecting keyword_end
       'solr_dataconfig': {
                         ^
/home/mblaho/vcsmap/lib/plugin_list.rb:23: syntax error, unexpected ',', expecting keyword_end
/home/mblaho/vcsmap/lib/plugin_list.rb:24: syntax error, unexpected ':', expecting keyword_end
       'sublime_github': {
                        ^
/home/mblaho/vcsmap/lib/plugin_list.rb:28: syntax error, unexpected ',', expecting keyword_end
/home/mblaho/vcsmap/lib/plugin_list.rb:29: syntax error, unexpected ':', expecting keyword_end
       'facebook_secrets': {
                          ^
/home/mblaho/vcsmap/lib/plugin_list.rb:34: syntax error, unexpected '}', expecting keyword_end
    from vcsmap.rb:11:in `<main>'
mblaho@MBlahoCarbon:~/vcsmap$
```

I attempted to look through the plugin_list.rb file to see if there was a syntax error, but I cannot find it. 

Ruby version: `ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]`
Bundler version:  1.12.5

**Comment by melvinsh** [comment]
I just pushed a [possible fix](https://github.com/melvinsh/vcsmap/commit/5419679735937095bb5cb9f23a33c812bb11c850). @MBLAHO13 could you verify?

**Comment by melvinsh** [comment]
Assuming this is fixed. Please let me know if this is not the case.
